export default function HomePage() {
  return (
    <div className="p-6 text-white">
      <h1 className="text-3xl font-bold mb-4">Welcome to TOBI TECH Assistant 👋</h1>
      <p className="text-lg mb-6">
        Your AI-powered assistant that helps you generate content, automate Telegram posts, send email campaigns, and manage your social media tasks — all in one dashboard.
      </p>

      <div className="grid gap-4 sm:grid-cols-2">
        <div className="bg-gray-800 p-4 rounded-xl shadow">
          <h2 className="text-xl font-semibold mb-2">📢 Ad Generator</h2>
          <p>Generate and customize social media ads from form submissions or content ideas.</p>
        </div>
        <div className="bg-gray-800 p-4 rounded-xl shadow">
          <h2 className="text-xl font-semibold mb-2">🧠 Daily Content Ideas</h2>
          <p>Receive daily ideas for Facebook, Instagram, Twitter/X, and WhatsApp — 3 per day.</p>
        </div>
        <div className="bg-gray-800 p-4 rounded-xl shadow">
          <h2 className="text-xl font-semibold mb-2">💬 Chat with Assistant</h2>
          <p>Get AI suggestions, edit drafts, and ask for help like you're talking to a real assistant.</p>
        </div>
        <div className="bg-gray-800 p-4 rounded-xl shadow">
          <h2 className="text-xl font-semibold mb-2">📨 Email Campaigns</h2>
          <p>Send automated emails to your contact list with campaigns generated by AI.</p>
        </div>
      </div>
    </div>
  );
}
